#!/bin/bash

function lint_config() {
  yamllint sample.yml
}

function lint_scripts() {
  pipenv run lint
  mypy --ignore-missing-imports kamoshika
  mypy tests
}

function main() {
  lint_config
  lint_scripts
}

main "$@"
